export const CommandTypes = Object.freeze({
  ROUTE_START: 'ROUTE_START',
  ROUTE_SEGMENT_ADD: 'ROUTE_SEGMENT_ADD',
  ROUTE_SEGMENT_EDIT: 'ROUTE_SEGMENT_EDIT',
  ROUTE_NODE_MOVE: 'ROUTE_NODE_MOVE',
  ROUTE_SPLIT_SEGMENT: 'ROUTE_SPLIT_SEGMENT',
  ROUTE_DELETE: 'ROUTE_DELETE',
  INSERT_COMPONENT: 'INSERT_COMPONENT',
  DELETE_COMPONENT: 'DELETE_COMPONENT',
});
